version: 2.1.{build}
branches:
  only:
  - develop
  - master
skip_tags: true
image: Visual Studio 2017
before_build:
- cmd: nuget.exe restore
build:
  project: Microsoft_Azure_Amqp.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    %xunit20%\xunit.console.x86.exe test\Test.Microsoft.Amqp\bin\Debug\net452\Test.Microsoft.Amqp.dll


    dotnet.exe test test\Test.Microsoft.Amqp.Core\Test.Microsoft.Amqp.Core.csproj
on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))