// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace amqplib_generator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using amqplib_generator;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class amqp_definitions_c : amqp_definitions_cBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 8 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 amqp amqp = Program.LoadAMQPTypes(); 
            
            #line default
            #line hidden
            this.Write("\r\n#include \"amqpvalue.h\"\r\n#include \"amqp_definitions.h\"\r\n#include <stdlib.h>\r\n#in" +
                    "clude <stdbool.h>\r\n\r\n");
            
            #line 15 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
	foreach (section section in amqp.Items.Where(item => item is section)) 
            
            #line default
            #line hidden
            
            #line 16 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
	{ 
            
            #line default
            #line hidden
            
            #line 17 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
		List<type> types = new List<type>(); 
            
            #line default
            #line hidden
            
            #line 18 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
		types.AddRange(section.Items.Where(item => item is type).Cast<type>()); 
            
            #line default
            #line hidden
            
            #line 19 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
		foreach (type type in types) 
            
            #line default
            #line hidden
            
            #line 20 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
		{ 
            
            #line default
            #line hidden
            
            #line 21 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
			string type_name = type.name.ToLower().Replace('-', '_'); 
            
            #line default
            #line hidden
            
            #line 22 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
			if (type.@class == typeClass.composite) 
            
            #line default
            #line hidden
            
            #line 23 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
			{ 
            
            #line default
            #line hidden
            
            #line 24 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				var descriptor = type.Items.Where(item => item is descriptor).First() as descriptor; 
            
            #line default
            #line hidden
            this.Write("/* ");
            
            #line 25 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.name));
            
            #line default
            #line hidden
            this.Write(" */\r\n\r\n\ttypedef struct ");
            
            #line 27 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE_TAG\r\n\t{\r\n\t\tAMQP_VALUE composite_value;\r\n\t} ");
            
            #line 30 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE;\r\n\r\n");
            
            #line 32 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				string arg_list = Program.GetMandatoryArgList(type); 
            
            #line default
            #line hidden
            
            #line 33 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				field[] mandatory_args = Program.GetMandatoryArgs(type).ToArray(); 
            
            #line default
            #line hidden
            this.Write("\tstatic ");
            
            #line 34 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 34 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_create_internal(void)\r\n\t{\r\n\t\t");
            
            #line 36 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 36 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 36 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)malloc(sizeof(");
            
            #line 36 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE));\r\n\t\tif (");
            
            #line 37 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance != NULL)\r\n\t\t{\r\n\t\t\t");
            
            #line 39 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value = amqpvalue_create_composite_with_ulong_descriptor(");
            
            #line 39 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(Program.GetDescriptor(type))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\tif (");
            
            #line 40 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value == NULL)\r\n\t\t\t{\r\n\t\t\t\tfree(");
            
            #line 42 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance);\r\n\t\t\t\t");
            
            #line 43 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = NULL;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\treturn ");
            
            #line 47 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance;\r\n\t}\r\n\r\n\t");
            
            #line 50 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 50 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_create(");
            
            #line 50 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arg_list));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\t");
            
            #line 52 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 52 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 52 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)malloc(sizeof(");
            
            #line 52 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE));\r\n\t\tif (");
            
            #line 53 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance != NULL)\r\n\t\t{\r\n\t\t\t");
            
            #line 55 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value = amqpvalue_create_composite_with_ulong_descriptor(");
            
            #line 55 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(Program.GetDescriptor(type))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\tif (");
            
            #line 56 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value == NULL)\r\n\t\t\t{\r\n\t\t\t\tfree(");
            
            #line 58 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance);\r\n\t\t\t\t");
            
            #line 59 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = NULL;\r\n\t\t\t}\r\n");
            
            #line 61 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				if (mandatory_args.Count() > 0) 
            
            #line default
            #line hidden
            
            #line 62 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				{ 
            
            #line default
            #line hidden
            this.Write("\t\t\telse\r\n\t\t\t{\r\n");
            
            #line 65 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					for (int i = 0; i < mandatory_args.Count(); i++) 
            
            #line default
            #line hidden
            
            #line 66 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            
            #line 67 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
						string mandatory_arg_name = mandatory_args[i].name.ToLower().Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tAMQP_VALUE ");
            
            #line 68 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value;\r\n");
            
            #line 69 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tint result = 0;\r\n\r\n");
            
            #line 72 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					for (int i = 0; i < mandatory_args.Count(); i++) 
            
            #line default
            #line hidden
            
            #line 73 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            
            #line 74 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
						string mandatory_arg_type = Program.GetCType(mandatory_args[i].type.ToLower()).Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            
            #line 75 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
						string mandatory_arg_name = mandatory_args[i].name.ToLower().Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 76 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value = amqpvalue_create_");
            
            #line 76 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_args[i].type.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 76 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_args[i].name.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("_value);\r\n\t\t\t\tif ((result == 0) && (amqpvalue_set_composite_item(");
            
            #line 77 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value, ");
            
            #line 77 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 77 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value) != 0))\r\n\t\t\t\t{\r\n\t\t\t\t\tresult = __LINE__;\r\n\t\t\t\t}\r\n");
            
            #line 81 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 83 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					for (int i = 0; i < mandatory_args.Count(); i++) 
            
            #line default
            #line hidden
            
            #line 84 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            
            #line 85 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
						string mandatory_arg_name = mandatory_args[i].name.ToLower().Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tamqpvalue_destroy(");
            
            #line 86 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value);\r\n");
            
            #line 87 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n");
            
            #line 89 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\treturn ");
            
            #line 92 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance;\r\n\t}\r\n\r\n\tvoid ");
            
            #line 95 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(");
            
            #line 95 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 95 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\tif (");
            
            #line 97 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(" != NULL)\r\n\t\t{\r\n\t\t\t");
            
            #line 99 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 99 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 99 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 99 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\tamqpvalue_destroy(");
            
            #line 100 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value);\r\n\t\t}\r\n\t}\r\n\r\n\tAMQP_VALUE amqpvalue_create_");
            
            #line 104 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 104 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 104 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\tAMQP_VALUE result;\r\n\r\n\t\tif (");
            
            #line 108 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(" == NULL)\r\n\t\t{\r\n\t\t\tresult = NULL;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\t");
            
            #line 114 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 114 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 114 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 114 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\tresult = amqpvalue_clone(");
            
            #line 115 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value);\r\n\t\t}\r\n\r\n\t\treturn result;\r\n\t}\r\n\r\n\tbool is_");
            
            #line 121 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_type_by_descriptor(AMQP_VALUE descriptor)\r\n\t{\r\n\t\tbool result;\r\n\r\n\t\tuint64_t desc" +
                    "riptor_ulong;\r\n\t\tif ((amqpvalue_get_ulong(descriptor, &descriptor_ulong) == 0) &" +
                    "&\r\n\t\t\t(descriptor_ulong == ");
            
            #line 127 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(descriptor).ToString()));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t{\r\n\t\t\tresult = true;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tresult = false;\r\n\t\t}\r\n\r\n\t\treturn" +
                    " result;\r\n\t}\r\n\r\n\r\n\tint amqpvalue_get_");
            
            #line 140 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("(AMQP_VALUE value, ");
            
            #line 140 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE* ");
            
            #line 140 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_handle)\r\n\t{\r\n\t\tint result;\r\n\t\t*");
            
            #line 143 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_handle = ");
            
            #line 143 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_create_internal();\r\n\t\tif (*");
            
            #line 144 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_handle != NULL)\r\n\t\t{\r\n\t\t\tAMQP_VALUE list_value = amqpvalue_get_described_value(v" +
                    "alue);\r\n\t\t\tif (list_value == NULL)\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 149 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(*");
            
            #line 149 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_handle);\r\n\t\t\t\tresult = __LINE__;\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\tAMQP_VALUE item_value" +
                    ";\r\n\t\t\t\tdo\r\n\t\t\t\t{\r\n");
            
            #line 157 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				int k = 0; 
            
            #line default
            #line hidden
            
            #line 158 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				foreach (field field in type.Items.Where(item => item is field)) 
            
            #line default
            #line hidden
            
            #line 159 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				{ 
            
            #line default
            #line hidden
            
            #line 160 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					string field_name = field.name.ToLower().Replace('-', '_'); 
            
            #line default
            #line hidden
            
            #line 161 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					string c_type = Program.GetCType(field.type).Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            
            #line 162 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					type field_type = Program.GetTypeByName(types, field.type); 
            
            #line default
            #line hidden
            
            #line 163 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					if ((field_type != null) && (field_type.@class == typeClass.composite)) c_type = field_type.name.ToUpper().Replace('-', '_').Replace(':', '_') + "_HANDLE"; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t/* ");
            
            #line 164 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.name));
            
            #line default
            #line hidden
            this.Write(" */\r\n\t\t\t\t\titem_value = amqpvalue_get_list_item(list_value, ");
            
            #line 165 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(k));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\tif (item_value == NULL)\r\n\t\t\t\t\t{\r\n");
            
            #line 168 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					if (field.mandatory == "true") 
            
            #line default
            #line hidden
            
            #line 169 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t");
            
            #line 171 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(*");
            
            #line 171 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_handle);\r\n\t\t\t\t\t\t\tresult = __LINE__;\r\n\t\t\t\t\t\t\tbreak;\r\n\t\t\t\t\t\t}\r\n");
            
            #line 175 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					} 
            
            #line default
            #line hidden
            
            #line 176 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					else 
            
            #line default
            #line hidden
            
            #line 177 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t/* do nothing */\r\n");
            
            #line 179 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t}\r\n\t\t\t\t\telse\r\n\t\t\t\t\t{\r\n");
            
            #line 183 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 if (field.type != "*") 
            
            #line default
            #line hidden
            
            #line 184 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 185 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c_type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 185 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\tif (amqpvalue_get_");
            
            #line 186 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.type.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(item_value, &");
            
            #line 186 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write(") != 0)\r\n\t\t\t\t\t\t{\r\n");
            
            #line 188 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					if (field.mandatory == "true") 
            
            #line default
            #line hidden
            
            #line 189 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 190 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(*");
            
            #line 190 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_handle);\r\n\t\t\t\t\t\t\tresult = __LINE__;\r\n\t\t\t\t\t\t\tbreak;\r\n");
            
            #line 193 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					} 
            
            #line default
            #line hidden
            
            #line 194 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					else 
            
            #line default
            #line hidden
            
            #line 195 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\tif (amqpvalue_get_type(item_value) != AMQP_TYPE_NULL)\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t");
            
            #line 198 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(*");
            
            #line 198 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_handle);\r\n\t\t\t\t\t\t\t\tresult = __LINE__;\r\n\t\t\t\t\t\t\t\tbreak;\r\n\t\t\t\t\t\t\t}\r\n");
            
            #line 202 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 					} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t}\r\n");
            
            #line 204 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 } 
            
            #line default
            #line hidden
            
            #line 205 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 else 
            
            #line default
            #line hidden
            
            #line 206 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 { 
            
            #line default
            #line hidden
            
            #line 207 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t}\r\n");
            
            #line 209 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					k++; 
            
            #line default
            #line hidden
            
            #line 210 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				} 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\tresult = 0;\r\n\t\t\t\t} while (0);\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\treturn result;\r\n\t}\r\n\r\n");
            
            #line 220 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				int j = 0; 
            
            #line default
            #line hidden
            
            #line 221 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				foreach (field field in type.Items.Where(item => item is field)) 
            
            #line default
            #line hidden
            
            #line 222 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				{ 
            
            #line default
            #line hidden
            
            #line 223 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					string field_name = field.name.ToLower().Replace('-', '_'); 
            
            #line default
            #line hidden
            
            #line 224 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					string c_type = Program.GetCType(field.type).Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            
            #line 225 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					type field_type = Program.GetTypeByName(types, field.type); 
            
            #line default
            #line hidden
            
            #line 226 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					if ((field_type != null) && (field_type.@class == typeClass.composite)) c_type = field_type.name.ToUpper().Replace('-', '_').Replace(':', '_') + "_HANDLE"; 
            
            #line default
            #line hidden
            this.Write("\tint ");
            
            #line 227 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_get_");
            
            #line 227 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 227 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 227 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 227 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c_type));
            
            #line default
            #line hidden
            this.Write("* ");
            
            #line 227 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value)\r\n\t{\r\n\t\tint result;\r\n\r\n\t\tif (");
            
            #line 231 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(" == NULL)\r\n\t\t{\r\n\t\t\tresult = __LINE__;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\t");
            
            #line 237 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 237 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 237 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 237 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\tresult = 0;\r\n\t\t}\r\n\r\n\t\treturn result;\r\n\t}\r\n\r\n\tint ");
            
            #line 244 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_set_");
            
            #line 244 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 244 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 244 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 244 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c_type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 244 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value)\r\n\t{\r\n\t\tint result;\r\n\r\n\t\tif (");
            
            #line 248 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(" == NULL)\r\n\t\t{\r\n\t\t\tresult = __LINE__;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\t");
            
            #line 254 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 254 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 254 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 254 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 255 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 if (c_type != "AMQP_VALUE") 
            
            #line default
            #line hidden
            
            #line 256 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 { 
            
            #line default
            #line hidden
            this.Write("\t\t\tAMQP_VALUE ");
            
            #line 257 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value = amqpvalue_create_");
            
            #line 257 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.type.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 257 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value);\r\n");
            
            #line 258 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 } 
            
            #line default
            #line hidden
            
            #line 259 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 else 
            
            #line default
            #line hidden
            
            #line 260 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 { 
            
            #line default
            #line hidden
            this.Write("\t\t\tAMQP_VALUE ");
            
            #line 261 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value = amqpvalue_clone(");
            
            #line 261 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value);\r\n");
            
            #line 262 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tif ((");
            
            #line 263 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value == NULL) ||\r\n\t\t\t\t(amqpvalue_set_composite_item(");
            
            #line 264 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value, ");
            
            #line 264 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 264 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value) != 0))\r\n\t\t\t{\r\n\t\t\t\tresult = __LINE__;\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\tresul" +
                    "t = 0;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\treturn result;\r\n\t}\r\n\r\n");
            
            #line 277 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
					j++; 
            
            #line default
            #line hidden
            
            #line 278 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
				} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 280 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
			} 
            
            #line default
            #line hidden
            
            #line 281 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
		} 
            
            #line default
            #line hidden
            
            #line 282 "D:\AMQPLib\amqplib_generator\amqp_definitions_c.tt"
	} 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class amqp_definitions_cBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
